---
title: "Moss Manuscript Statistical Tables"
author: "Andrew Kleinhesselink"
date: "12/18/2018"
output: word_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(tidyverse)


lm_capt_str <- 'Residual standard error: %.5f on %1.f degrees of freedom.
Multiple R-squared %.5f, Adjusted R-squared: %.5f.
F-statistic: %.1f on %1.f and %1.f DF, p-value: %e.'

glm_binom_str <- 'Residual standard error: %.5f on %1.f degrees of freedom.
Multiple R-squared %.5f, Adjusted R-squared: %.5f.
F-statistic: %.1f on %1.f and %1.f DF, p-value: %e.'


val_order <- c('sigma', 
             'df.residual',
             'r.squared',
             'adj.r.squared',
             'statistic',
             'df',
             'df.residual',
             'p.value')

load(file = '~/Dropbox/projects/moss_manuscript/output/point_intercept_models.rda')

# Table functions ---------------------------- # 
print_glm_table <- function(glm_model, title){
  
  my_tab <- broom::tidy(glm_model)
  
  knitr::kable(my_tab, digits = c(3, 3, 2, 2), caption = title)
}

print_glm_table_caption <- function( glm_model, mystr ) {
  
  mod_glance <- 
    broom::glance(glm_model)  %>%    
    gather(stat, val) 
   
  quickstats <- mod_glance$val
  names( quickstats ) <- mod_glance$stat
   
  mynums <- as.list(quickstats[val_order])
   
  my_caption <- do.call(sprintf, c(mystr, mynums))

  knitr::asis_output(my_caption)
}

```


```{r echo = F}

print_glm_table(moss_cover_lm, 'Table 1. Moss Cover on Gradient' )
print_glm_table_caption( moss_cover_lm, capt_str)

```

----------------------------------- 

```{r echo = F}

print_glm_table(all_hits_glm, 'Table 2. Plant occurence in moss across the gradient')
print_glm_table_caption( all_hits_glm, capt_str)

summary(all_hits_glm)
```

