#source('code/moss_removal_analysis.R')

rm(list = ls())

library(tidyverse)
library(scales)
library(grid)
library(gridExtra)

source('code/moss_theme.R')

load('output/processed_experiment_data.rda') # saved data is generated by the moss_removal_analysis script 

#### plot parameters
xTitle = "Position on environmental gradient"
yTitle1 = 'Percent survival'
yTitle2 = 'Mean plant size (log g)\n'
yTitle3 = 'Inflorescences per plant (no.)\n'


label_df <- data.frame(label = c('a)', 
                                 'b)', 
                                 'c)', 
                                 'd)', 
                                 'e)', 
                                 'f)'), 
                       species = c('Bromus', 
                                   'Vulpia'), 
                       x_pos = 0.6, 
                       y_pos = 1, 
                       Treatment = 'Moss patch')


prop_success$measure <- 'success'
size$measure <- 'size'
infls$measure <- 'infls'
fig2 <- 
  ggplot(data = size, aes( x = Stress, y = result, ymin = result - stand_err, 
                           ymax = result + stand_err, group = Treatment, 
                           color = Treatment, shape = Treatment)) + 
  geom_point(position = position_dodge(width = 0.2), size = 4) + 
  geom_line(stat = 'identity', position = position_dodge( width = 0.2)) + 
  geom_errorbar (position = position_dodge(), width = 0.2) + 
  geom_text(data = label_df[3:4,], aes( x = x_pos, y = y_pos*max(size$result) + 0.3, label = label, ymin = 0, ymax = 0), size = 5, vjust = 0.1, show.legend = FALSE) + 
  scale_y_continuous(yTitle2) + 
  xlab(xTitle) + 
  scale_shape_manual(values = c(19, 2, 0))  + 
  scale_color_manual(values = c('black', 'black', 'black')) + 
  guides(color = guide_legend(override.aes = list(linetype = 0, size = 5))) +
  facet_grid( . ~ species) +   
  moss_theme


brdi <- read_csv('data/brdi_data.csv')
vusp <- read_csv('data/vulpia_data.csv')

brdi$species <- 'Bromus'
vusp$species <- 'Vulpia'

rawdata <- rbind(brdi, vusp) %>% 
  mutate( Stress = factor(stress, labels = c('High stress', 'Low stress'))) %>% 
  mutate( Treatment = factor(treatment, levels = c('MC', 'BC', 'MR'), labels = c('Moss patch', 'Bare sand', 'Moss removed'), ordered = T)) %>% 
  mutate( result = log(mass_per_plant_mg))



fig2  + 
  geom_point(dat = rawdata, aes( x = Stress, y = result, ymin = 0, ymax = 0), position = position_dodge(width = 0.2))


    
